# Generated by Django 5.0.2 on 2024-02-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='craeyed',
            new_name='created',
        ),
    ]
